# Generated by Django 5.0.2 on 2024-02-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_remove_agents_fonction_delete_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='nom',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='agents',
            name='post_nom',
            field=models.CharField(max_length=30),
        ),
    ]
