# Generated by Django 5.0.2 on 2024-02-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docteurs', '0003_remove_docteur_id_docteur_agents_ptr'),
        ('infirmiers', '0002_remove_infirmiers_id_infirmiers_agents_ptr'),
        ('malade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malade',
            name='docteur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docteurs.docteur'),
        ),
        migrations.AlterField(
            model_name='malade',
            name='infirmier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='infirmiers.infirmiers'),
        ),
    ]
