# Generated by Django 5.0.2 on 2024-02-27 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infirmiers', '0002_remove_infirmiers_id_infirmiers_agents_ptr'),
        ('malade', '0005_malade_infirmier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malade',
            name='infirmier',
        ),
        migrations.AddField(
            model_name='malade',
            name='infirmier',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='infirmiers.infirmiers'),
            preserve_default=False,
        ),
    ]
