# Generated by Django 5.0.2 on 2024-02-27 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('infirmiers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infirmiers',
            name='id',
        ),
        migrations.AddField(
            model_name='infirmiers',
            name='agents_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agents.agents'),
            preserve_default=False,
        ),
    ]
