# Generated by Django 5.0.2 on 2024-02-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docteurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docteur',
            options={'verbose_name': 'Docteur', 'verbose_name_plural': 'Docteurs'},
        ),
    ]
